<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Chapa\\Model\\' => array($vendorDir . '/src/Models'),
    'Chapa\\Controller\\' => array($vendorDir . '/src/Controllers'),
    'Chapa\\Chapa\\' => array($vendorDir . '/src'),
);
