<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit88c76c41a340851307d188b394405c1a
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Chapa\\Model\\' => 12,
            'Chapa\\Controller\\' => 17,
            'Chapa\\Chapa\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Chapa\\Model\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Models',
        ),
        'Chapa\\Controller\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/Controllers',
        ),
        'Chapa\\Chapa\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit88c76c41a340851307d188b394405c1a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit88c76c41a340851307d188b394405c1a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit88c76c41a340851307d188b394405c1a::$classMap;

        }, null, ClassLoader::class);
    }
}
